name: CI for Server and Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for server
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Run server tests
        working-directory: ./server
      - run: |
          touch .env
          echo "${{ secrets.MONGODB_URL }}" > .env

  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for client
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install client dependencies
        run: npm install
        working-directory: ./toDoList

      - name: Run client tests
        working-directory: ./toDoList
