name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-server:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} for Server
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Server Dependencies
        run: |
          cd server
          npm ci

      - name: Set up Environment Variables for Server
        run: |
          cd server
          touch .env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env

      - name: Restart Server using PM2
        run: |
          cd server
          pm2 restart BackendAPI

  build-client:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} for Client
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Client Dependencies
        run: |
          cd toDoList
          npm ci

      - name: Run Client Tests
        run: |
          cd toDoList
          npm test

      - name: Start Client in Development Mode
        run: |
          cd toDoList
          npm run dev
